#pragma kernel CSMain
#include "fluid_utilities.cginc"


Texture2D<float4> source;
RWTexture2D<float4> target;
SamplerState LinearClamp;


float delta_time;

NUMTHREADS
void CSMain (uint3 id : SV_DispatchThreadID)
{


    float2 velocity = source[id.xy].xy;


    float2 backwards_pos = id.xy - velocity * delta_time;
	float2 new_vel = source.SampleLevel(LinearClamp, (backwards_pos+0.5)/GRID_SIZE,0).xy;
    target[id.xy] = float4(new_vel,0,0);
}
